NumTargets:                 4

MapTopic:                   '/voxel_map'

TargetTopic:                '/move_base_simple/goal'

OdomTopic:                  '/mavros/local_position/odom'

DilateRadius:               0.5

VoxelWidth:                 0.25

MapBound:                   [-25.0, 25.0, -25.0, 25.0, 0.0, 5.0]

TimeoutRRT:                 0.02

MaxVelMag:                  4.0

MaxBdrMag:                  2.1
# MaxBdrMag:                  3.84          # Iris

MaxTiltAngle:               1.05

MinThrust:                  2.0

# MaxThrust:                  12.0
MaxThrust:                  26.0          # Iris

# VehicleMass:                0.61
VehicleMass:                1.535         # Iris

GravAcc:                    9.8

HorizDrag:                  0.70

VertDrag:                   0.80

ParasDrag:                  0.01

SpeedEps:                   0.0001

WeightT:                    20.0

ChiVec:                     [1.0e+4, 1.0e+4, 1.0e+4, 1.0e+4, 1.0e+5]

SmoothingEps:               1.0e-2

IntegralIntervs:            16

RelCostTol:                 1.0e-5

## Modelling Parameters
ModelType:                  2
# Ellipsoid
HorizHalfLen:               0.25
VertHalfLen:                0.075

# Rectangular Box
RectangularBox:             [0.47, 0.47, 0.11]

## Visualizer
OdomFrame:                  'map'
TrajVizWidth:               1.0
TrajVizRGB:                 [0.8, 0.0, 0.0]
EllipsoidPath:              '/misc/sphere.stl'
EllipsoidVizRGBA:            [1.0, 0.0, 1.0, 1.0]
QuadrotorPath:              '/misc/quadcopter.dae'